### ISSUE TITLE
请问怎么修改默认的链接样式呢

### ISSUE THREAD

**Issue by zhonglebajian** [MaxsLi/WikipediaDarkTheme#5]
新手 很喜欢这个插件帮了大忙 了
下载了脚本 但是不知道怎么修改 想把默认的超链接样式修改一下 但是不知道怎么做。。
帮帮孩子

**Comment by li-shangru** [comment]
感谢使用！

在147行，function `applyDarkTheme` 里：

```js
if (!isSpecialElement(element)) {
    changeForegroundColor(element);
    changeBackgroundColor(element);
}
```
如果不是special element的话，我们就改变element的颜色，那么如果想要修改超链接的样式，就要把超链接归入special element：

在function `isSpecialElement(e)`中，加入一个function `elementIsHyperlink`:

```js
function isSpecialElement(e) {
    if (elementIsImage(e)) {
        changeImageIfOnLists(e);
        return true;
    } else if (elementIsHyperlink(e)) {
        // 改变 e 的颜色
        return true;
    } 
    ...
```

此时，我们就要自己来写`elementIsHyperlink`这个function:

```js
function elementIsHyperlink(e) {
    // return True 如果 e 是超链接
}
```

如何写这个function就交给你了，happy coding!

**Comment by li-shangru** [comment]
A settings modal was added for users to customize their own link color.
