### ISSUE TITLE
Wikipedia account breaks the settings button

### ISSUE THREAD

**Issue by Snapyou2** [MaxsLi/WikipediaDarkTheme#8]
Hey there, thanks for your work !
I was wondering if it was possible to add the settings button even if you're logged in with a wikipedia account + if it was possible to remove that ugly white menu bar when logged in and when the browser windows is shrinked (even if not logged in).
![image](https://user-images.githubusercontent.com/76458339/151445171-a946e15a-9d3f-456d-8d21-4ef31c077356.png)
A small advice in the readme would also help because I searched for the settings button like 10 minutes before thinking about logging off to see it appear.
Thanks a lot !

**Comment by li-shangru** [comment]
Hi there,

Thanks for using the script and really appreciate the feedback.

I can see you are using Wikipedia skins, it was my mistake for not taking this into consideration.

I have updated (3b4f643ce72a787874821225b54678eb5f8eacaf) the script and made improvements on all Wikipedia skins.

As well as fixing the issue where the settings button disappears after logging in.

Please update your script and check again.

Thank you!
