### ISSUE TITLE
Script misbehaves on etherpad

### ISSUE THREAD

**Issue by csavard-sudo** [MaxsLi/WikipediaDarkTheme#9]
The script causes pages on https://etherpad.wikimedia.org not to load correctly. 

For example on https://etherpad.wikimedia.org/p/wikimania2022-10-years-of-wikidata I get the error : 

"An error occurred while loading the page:

    TypeError: parentList is null

in https://etherpad.wikimedia.org/p/wikimania2022-sound-logo-roundtable line 14 > eval
at line 629:3

Stack trace:

    addSettingsButton@moz-extension://c45ac27d-99b0-4937-9224-58dd448cccb4/userscripts/Wikipedia%20Dark%20Theme.user.js?id=5056c159-2ff6-4f7d-b77c-8ee3e3ac83e9:629:3
    initSettingElements@moz-extension://c45ac27d-99b0-4937-9224-58dd448cccb4/userscripts/Wikipedia%20Dark%20Theme.user.js?id=5056c159-2ff6-4f7d-b77c-8ee3e3ac83e9:588:3
    tms_5056c159_2ff6_4f7d_b77c_8ee3e3ac83e9$/document.onreadystatechange@moz-extension://c45ac27d-99b0-4937-9224-58dd448cccb4/userscripts/Wikipedia%20Dark%20Theme.user.js?id=5056c159-2ff6-4f7d-b77c-8ee3e3ac83e9:119:7
"

**Comment by li-shangru** [comment]
Hi,

Thanks for using!

This issue was fixed in version 1.62, please update the script and try again.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/37417901/186239892-e457b7c7-1fe0-49d0-905b-3461293577ee.png">
